#!/bin/sh

files=$(git diff --staged --name-only --diff-filter=ACMR HEAD)

if [ -n "$files" ]
then
  echo "🤖 linting changed files..."

  if [ -f .git/MERGE_MSG ]
  then
    # Don't lint on merges, since there are likely to be
    # lots of changed files.
    bundle exec rubocop $files
  else
    bundle exec rubocop --auto-correct $files
  fi
fi
