#!/bin/sh

files=$(git diff --staged --name-only --diff-filter=ACMR HEAD)

if [ -n "$files" ]
then
  echo "🤖 linting changed files..."

  # Don't lint on merges, since there are likely to be
  # lots of changed files.
  if ! [ -f .git/MERGE_MSG ]
  then
    bundle exec rubocop --autocorrect --force-exclusion $files
  fi
fi
