#!/usr/bin/env bash

if [[ "${CODESPACES:-}" == 'true' ]]; then
  sudo apt-get -y update
  sudo apt-get -y install neovim

  echo "=== Installing Vundle ==="
  git clone "https://github.com/VundleVim/Vundle.vim.git" "$HOME/.vim/bundle/Vundle.vim"

  echo "=== Installing and configuring vim-plug ==="
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
