#!/usr/bin/env bash

if [[ "${CODESPACES:-}" == 'true' ]]; then
  echo "=== Installing neovim ==="
  curl -sSfLo  "${HOME}/tmp/nvim/nvim.appimage" --create-dirs https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  chmod u+x "${HOME}/tmp/nvim/nvim.appimage"
  ${HOME}/tmp/nvim/nvim.appimage --appimage-extract 1>/dev/null
  sudo mv squashfs-root /
  sudo ln -sf /squashfs-root/AppRun /usr/bin/nvim

  echo "=== Installing utilities ==="
  sudo apt-get update
  sudo apt-get install -y fzf silversearcher-ag
  sudo wget https://raw.githubusercontent.com/garybernhardt/selecta/master/selecta -O /usr/local/bin/selecta

  echo "=== Installing Vundle ==="
  git clone "https://github.com/VundleVim/Vundle.vim.git" "$HOME/.vim/bundle/Vundle.vim"

  echo "=== Installing and configuring vim-plug ==="
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi
